version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -q mkdocs mkdocs-material
      - run:
          name: Publish to gh-pages
          command: mkdocs gh-deploy -c
