version: 2.1

jobs:
  build-deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -q mkdocs mkdocs-material
      - run:
          name: Build & Publish to gh-pages
          command: mkdocs gh-deploy --dirty
workflows:
  build-deploy: # workflow label
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master